version: "3.6"
services:
  app:
    image: file-manager-client:latest
    container_name: file-manager-client
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.5"
          memory: 256M
    shm_size: 5120MB
    ports:
      - 8083:80
